include ../common.mk

TARGET = hello temperature copy wc power maxline

all: $(TARGET)

# use make defaule rules for single c source files
# $(TARGET): $(TARGET).c
# 	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ $^

clean:
	$(RM) $(TARGET)