site_name: Learning System Programming
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: learning-system-programming
repo_url: https://github.com/zhoujiagen/learning-system-programming

nav:
    - Home: index.md
    - Tools:
      - Home: tools/index.md
      - 'GNU toolchain':
        - Home: tools/gnu/gnu-toolchain.md
        - 'An Introduction to GCC': tools/gnu/gcc-intro.md
        - 'Make': tools/gnu/make.md
        - 'Managing Projects with GNU Make': tools/gnu/managing-projects-with-gnu-make.md
        - 'Autotools': tools/gnu/autotools.md
      - CMake: tools/cmake.md
      - 'C Tool': tools/c-tool.md
      - 'C++ Tool': tools/cpp-tool.md
      - Ninja: tools/ninja.md
      - LLVM:
        - 'Home': tools/llvm/llvm.md
        - 'LLVM Essentials': tools/llvm/llvm-essentials.md
        - 'LLVM Paper': tools/llvm/llvm-paper.md
        - 'LLVM Core Libraries': tools/llvm/llvm-core-libraries.md
    - 'Architecture':
      - 'System V Application Binary Interface': architecture/ABI.md 
      - 'The Linux Kernel CPU Architectures': architecture/linux-cpu-architecture.md
      - 'Intel':
        - 'Volume 1: Basic Architecture': architecture/intel/vol1-basic-architecture.md
        - 'Volume 3A: System Programming Guide': architecture/intel/vol3a-system-programming-guide.md
        - 'Volume 3B: System Programming Guide': architecture/intel/vol3b-system-programming-guide.md
    - Compiler:
      - 'References': compiler/Engineering-a-Compiler-refs.md
    - Assembly:
      - Home: assembly/index.md
      - 'Professional Assembly Language': assembly/pro-assembly.md
      - 'NASM': assembly/nasm.md
      - 'Assembly Language Step-by-Step': assembly/assembly-step-by-step.md
      - 'Instructions': assembly/instructions.md
    - C:
      - Home: c/index.md
      - 'Core': c/clang-core.md
    - 'C++':
      - Home: cpp/index.md
      - 'Q&A': cpp/QA.md
      - 'C++ 11': cpp/CXX11-Standard.md
    - 'Kernel':
      - Home: kernel/index.md
      - 'Linux Referenced Specifications': kernel/linux-ref-spec.md
      - 'Linux Standard Base': kernel/linux-standard-base.md
      - 'Linux手册页': kernel/linux-man.md
      - '系统调用': kernel/syscall.md
      - 'UNIX环境高级编程': kernel/apue.md
      - 'Linux编程接口': kernel/tlpi.md
      - 'Linux内核设计与实现':
        - 'Home': kernel/kernel-dev/kernel-dev.md
        - 'Part 1': kernel/kernel-dev/kernel-dev1.md
        - 'Part 2': kernel/kernel-dev/kernel-dev2.md
      - '深入Linux内核架构': kernel/linux-arch.md
      - '网络':
        - 'TCP/IP': kernel/network/network.md
        - 'Netty': kernel/network/netty.md
        - 'NS2': kernel/network/ns2.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
