site_name: Learning System Programming
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: learning-system-programming
repo_url: https://github.com/zhoujiagen/learning-system-programming

nav:
    - Home: index.md
    - Tools:
      - Home: tools/index.md
      - 'GNU':
        - 'Toolchain': tools/gnu/gnu-toolchain.md
        - 'An Introduction to GCC': tools/gnu/gcc-intro.md
        - '深入分析GCC': tools/gnu/gcc-analysis.md
        - 'glibc': tools/gnu/gnu-glibc.md
        - 'Managing Projects with GNU Make': tools/gnu/gnu-make.md
        - 'Autotools': tools/gnu/gnu-autotools.md
      - 'Programming':
        - 'C Tool': tools/programming/c-tool.md
        - 'C++ Tool': tools/programming/cpp-tool.md
        - CMake:
          - 'Mastering CMake': tools/programming/cmake/mastering-cmake.md
          - 'References':
            - Home: tools/programming/cmake/refs/index.md
            - 'Variables': tools/programming/cmake/refs/cmake-variables.md
            - 'Commands': tools/programming/cmake/refs/cmake-commands.md
            - 'Modules': tools/programming/cmake/refs/cmake-modules.md
        - Ninja: tools/programming/ninja.md
    - 'Architecture':
      - Home: architecture/index.md
      - 'Low-Level Programming': architecture/Low-Level-Programming.md
      - 'System V Application Binary Interface': architecture/ABI.md
      - 'The Linux Kernel CPU Architectures': architecture/linux-cpu-architecture.md
      - 'Intel':
        - 'Volume 1: Basic Architecture': architecture/intel/vol1-basic-architecture.md
        - 'Volume 3A: System Programming Guide': architecture/intel/vol3a-system-programming-guide.md
        - 'Volume 3B: System Programming Guide': architecture/intel/vol3b-system-programming-guide.md
    - Assembly:
      - Home: assembly/index.md
      - 'Professional Assembly Language': assembly/pro-assembly.md
      - 'NASM': assembly/nasm.md
      - 'Assembly Language Step-by-Step': assembly/assembly-step-by-step.md
      - 'Instructions': assembly/instructions.md
    - C:
      - Home: c/index.md
      - 'Headers': c/c-headers.md
      - 'Core': c/c-core.md
    - 'C++':
      - Home: cpp/index.md
      - 'Programming: Principles and Practice Using C++':
        - 'Home': cpp/PPP2/PPP2.md
        - 'Part I The Basics': cpp/PPP2/PPP2-1-The-Basics.md
        - 'Part II Input and Output': cpp/PPP2/PPP2-2-Input-and-Output.md
        - 'Part III Data and Algorithms': cpp/PPP2/PPP2-3-Data-and-Algorithms.md
        - 'Part IV Broadening the View': cpp/PPP2/PPP2-4-Broadening-the-View.md
        - 'Part V Appendices': cpp/PPP2/PPP2-5-Appendices.md
      - 'C++ Primer':
        - 'Home': cpp/CP5/CP5.md
        - 'Part I The Basics': cpp/CP5/CP5-1-The-Basics.md
        - 'Part II The C++ Library': cpp/CP5/CP5-2-The-Cpp-Library.md
        - 'Part III Tools for Class Authors': cpp/CP5/CP5-3-Tools-for-class-authors.md
        - 'Part IV Advanced Topics': cpp/CP5/CP5-4-Advanced-Topics.md
      - 'Q&A': cpp/QA.md
      - 'C++ 11': cpp/CXX11-Standard.md
      - 'C++ Concurrency in Action': cpp/cpp_concurrency.md
    - 'Kernel':
      - Home: kernel/index.md
      - 'Programming':
        - 'UNIX环境高级编程': kernel/programming/apue.md
        - 'Linux编程接口': kernel/programming/tlpi.md
        - '系统调用': kernel/programming/syscall.md
      - 'Linux Specifications':
        - 'Linux手册页': kernel/specification/linux-man.md
        - 'Linux Standard Base': kernel/specification/linux-standard-base.md
        - 'Linux Referenced Specifications': kernel/specification/linux-ref-spec.md
      - 'Linux Architecture':
        - 'Linux内核设计与实现':
          - 'Home': kernel/linux-arch/kernel-dev/kernel-dev.md
          - 'Part 1': kernel/linux-arch/kernel-dev/kernel-dev1.md
          - 'Part 2': kernel/linux-arch/kernel-dev/kernel-dev2.md
          - '深入Linux内核架构': kernel/linux-arch/linux-arch.md
          - 'Linux内核设计的艺术': kernel/linux-arch/linux-0.11.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
