include ../common-c.mk

TARGET = struct_anon struct_named struct_namespace struct_typedef struct_init\
	union_example \
	anon \
	enum_example \
	macro_str macro_concat \
	c_parametric_polymorphism c_inclusion c_overload

all: $(TARGET)

clean:
	$(RM) $(TARGET)
